version: 1.0.{build}
init:
  clone_depth: 1
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      qt: 5.10.0\msvc2017_64
      VS_VERSION: 2017
      BUILD_ARCH: x64
configuration:
  - Release
install:
- git submodule update --init --recursive --depth 1
- set PATH=%PATH%;C:\Qt\%qt%\bin;
- IF "%VS_VERSION%" == "2017" (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" && qmake.exe -tp vc -r) ELSE (qmake.exe -tp vc -r)
build:
  parallel: true
  verbosity: minimal